version: '3.6'

services:
  web:
    build: angular-front/.
    volumes:
      - ./angular-front/.:/blog/
    working_dir: /blog
    command: ng serve -host 0.0.0.0
    ports:
      - 4200:4200
    depends_on:
      - api
  api:
    build: rails-api/.
    volumes:
      - ./rails-api/.:/app/
    working_dir: /app
    command: puma
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres@db
  db:
    image: postgres:10.3-alpine
